### ISSUE TITLE
Things to Fix/Add

### ISSUE THREAD

**Issue by alyeffy** [andrewgrant111/carecircles#1]
Hey guys! We should work together to clean up the site. We should start by making a list and assigning things for each of us to do.

***BUGS***
[ ]
[ ]
[ ]
[ ]
[ ]

***FEATURES***
[ ]
[ ]
[ ]
[ ]
[ ]

**Comment by andrewgrant111** [comment]
Do you think we could do this in slack? I know it will be less traceable, but it means we don't have to use another communication platform and we can keep Katherine and others involved

**Comment by alyeffy** [comment]
Sounds good!
